### ISSUE TITLE
Cart item Caching issue

### ISSUE THREAD

**Issue by pschandekar** [VirtoCommerce/vc-theme-material#13]
Hi,
Below are the image links -

 Notice that the shopping cart shows 0 but the cart actually has 4 (same item added 4 times by pressing back)

We are using VC theme material.

![image2](https://user-images.githubusercontent.com/32933911/32940161-e7c6ca3e-cba7-11e7-8194-956b033f2d97.png)
![image1](https://user-images.githubusercontent.com/32933911/32940113-c528007e-cba7-11e7-912b-18352fbff207.png)

Thanks
Parshuram

**Comment by tatarincev** [comment]
We no longer support material theme
