### ISSUE TITLE
Migrate material theme to new storefront version with Scriban view engine

### ISSUE THREAD

**Issue by trueboroda** [VirtoCommerce/vc-theme-material#16]
The primary objective is allow to run the vc-theme-material with the new storefront that powered by new Scriban, end-user liquid template engine

Technical details:

- The new storefront version with Scriban engine can be taken from this branch https://github.com/VirtoCommerce/vc-storefront-core/tree/features/scriban-migration
- All theme changes should be performed in special branch scriban-migration in GitHub repository of this theme
- All known breaking changes related with new theme syntax are described in this issue VirtoCommerce/vc-storefront-core#188

**Comment by tatarincev** [comment]
released https://github.com/VirtoCommerce/vc-theme-material/releases/tag/v2.0.0
