### ISSUE TITLE
Error in 'option_selection.js' when open product page

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-material#4]
![screenshot 347](https://user-images.githubusercontent.com/6369252/29712536-c0aa4966-89b3-11e7-9c8d-5e77f0875000.png)

**Comment by vkrashenko** [comment]
![material1](https://user-images.githubusercontent.com/29459286/30863161-99795d88-a2d0-11e7-94b7-02d7157915c6.gif)

**Comment by asvishnyakov** [comment]
Fixed
