### ISSUE TITLE
Can't open registration page

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-material#5]
Open http://demo.virtocommerce.com/Clothing/Account/Login and click to "Create account". You will be redirectred to Electronics store (because of http://demo.virtocommerce.com/account/register url)

**Comment by vkrashenko** [comment]
![material2](https://user-images.githubusercontent.com/29459286/30863578-adc5477e-a2d1-11e7-9504-d540913d4d16.gif)

**Comment by asvishnyakov** [comment]
Fixed
