### ISSUE TITLE
Can't see exceptions

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-material#6]
When exception occurs, it displayed like this, without message:
![screenshot 349](https://user-images.githubusercontent.com/6369252/29712724-afb6fb80-89b4-11e7-893c-49d864a9ec46.png)

**Comment by vkrashenko** [comment]
![material4](https://user-images.githubusercontent.com/29459286/30869707-295eae10-a2e2-11e7-9caf-a5e46a7afa79.gif)

**Comment by asvishnyakov** [comment]
Fixed by @vkrashenko. Closed.
