### ISSUE TITLE
Can't register account

### ISSUE THREAD

**Issue by asvishnyakov** [VirtoCommerce/vc-theme-material#7]
Go to http://demo.virtocommerce.com/Clothing/Account/Register and try to register account. You will get this:
![screenshot 349](https://user-images.githubusercontent.com/6369252/29712751-d5edf696-89b4-11e7-9240-de94a24e1e93.png)

**Comment by vkrashenko** [comment]
![material3](https://user-images.githubusercontent.com/29459286/30863814-440ea586-a2d2-11e7-9b03-0753161f320e.gif)

**Comment by asvishnyakov** [comment]
Fixed
