### ISSUE TITLE
Color, size and price filters are not working in clothing theme

### ISSUE THREAD

**Issue by OlegoO** [VirtoCommerce/vc-theme-material#9]
@Woland2k commented on [Fri Jul 22 2016](https://github.com/VirtoCommerce/vc-platform/issues/558)

![image](https://cloud.githubusercontent.com/assets/1566470/17069118/baf71236-5009-11e6-9ec9-b068925b2db5.png)

Should be able to click colors, sizes, prices and brands to filter elements in clothing theme.

**Comment by tatarincev** [comment]
This issue has been closed because it has been inactive for  a long time
You may reopen this issue if it has been closed in error.
